uk:
  gov:
    hmcts:
      transform:
        caseTypeofApplication:
          C100:
            caseFields:
              CASE_TYPE_ID: PRLAPPS
              EVENT_ID: create-case-privatelaw-bs-c100
            caseDataFields:
              natureOfOrder: natureofOrder
              applicants:
                - value:
                    firstName: applicantOneFirstName
                    lastName: applicantOneLastName
                    previousName: applicantOnePreviousNames
                    gender: applicantOneGender
                    dateOfBirth: applicantOneDateOfBirth
                    placeOfBirth: applicantOnePlaceOfBirth
                    address:
                      AddressLine1: applicantOneAddress
                    #PostCode: applicantOneAddressPostCode
                    landline: applicantOneHomePhoneNumber
                    phoneNumber: applicantOneMobilePhoneNumber
                    email: applicantOneEmailAddress
                    #isAtAddressLessThan5Years: hasapplicantOneLivedAtThisAddressForOverFiveYears
                    addressLivedLessThan5YearsDetails: applicantOneAllAddressesForLastFiveYears
                    doTheyHaveLegalRepresentation: doYouHaveSolicitor
                    representativeFirstName: your_solicitor_name
                    solicitorOrg:
                          OrganisationName: solicitor_firm_name
                    solicitorAddress:
                          AddressLine1: solicitor_address
                          PostCode: solicitor_postcode
                    solicitorTelephone: solicitor_telephone_number
                    #solicitorFaxNumber: solicitor_fax_number
                    dxNumber: solicitor_dx_number
                    solicitorReference: solicitor_reference
                    #solicitorFeeAccount: solicitor_fee_account_No
                    solicitorEmail: solicitor_email_address
                - value:
                    firstName: applicantTwoFirstName
                    lastName: applicantTwoLastName
                    previousName: applicantTwoPreviousNames
                    gender: applicantTwoGender
                    dateOfBirth: applicantTwoDateOfBirth
                    placeOfBirth: applicantTwoPlaceOfBirth
                    address:
                      AddressLine1: applicantTwoAddress
                    #PostCode: applicantTwoAddressPostCode
                    landline: applicantTwoHomePhoneNumber
                    phoneNumber: applicantTwoMobilePhoneNumber
                    email: applicantTwoEmailAddress
                    #isAtAddressLessThan5Years: hasapplicantTwoLivedAtThisAddressForOverFiveYears
                    addressLivedLessThan5YearsDetails: applicantTwoAllAddressesForLastFiveYears
              children:
                - value:
                    firstName: child1_firstName
                    lastName: child1_lastName
                    dateOfBirth: child1_dateOfBirth
                    gender: child1_gender
                    applicantsRelationshipToChild: child1_applicant1_relationship
                    respondentsRelationshipToChild: child1_respondent1_relationship
                - value:
                    firstName: child2_firstName
                    lastName: child2_lastName
                    dateOfBirth: child2_dateOfBirth
                    gender: child2_gender
                    applicantsRelationshipToChild: child2_applicant1_relationship
                    respondentsRelationshipToChild: child2_respondent1_relationship
                - value:
                    firstName: child3_firstName
                    lastName: child3_lastName
                    dateOfBirth: child3_dateOfBirth
                    gender: child3_gender
                    applicantsRelationshipToChild: child3_applicant1_relationship
                    respondentsRelationshipToChild: child3_respondent1_relationship
                - value:
                    firstName: child4_firstName
                    lastName: child4_lastName
                    dateOfBirth: child4_dateOfBirth
                    gender: child4_gender
                    applicantsRelationshipToChild: child4_applicant1_relationship
                    respondentsRelationshipToChild: child4_respondent1_relationship
              childrenKnownToLocalAuthorityTextArea: child1_localAuthority_or_socialWorker
              parentalResponsibilityDetails: parentalResponsibilityDetails
              #childrenParentsName: children_parentsName
              childParentsNameCollection: child_parentsName_collection
              personWhoLivesWithChild: child_living_with_others_details
              applicationPermissionRequiredReason: permissionRequiredReason
              applicationDetails: briefDetailsOnTheApplication
              havePreviousParentingPlan: havePreviousParentingPlan
              #applicationPermissionRequired : askingPermissionForApplication
              #previousOrOngoingProceedings : previous_or_ongoingProceeding
              setOutReasonsBelow: null
              effortsMadeWithRespondents: respondent_effort
              doYouRequireAHearingWithReducedNotice: withoutNotice_abridged_or_informalNotice
              reasonsForApplicationWithoutNotice: reason_for_consideration
              c100RebuildHearingUrgency: urgency_reason

              respondents:
                - value:
                    firstName: respondentOneFirstName
                    lastName: respondentOneLastName
                    previousName: respondentOnePreviousNames
                    gender: respondentOneGender
                    dateOfBirth: respondentOneDateOfBirth
                    isDateOfBirthUnknown: respondentOneDateOfBirthDontKnow
                    placeOfBirth: respondentOnePlaceOfBirth
                    address:
                      AddressLine1: respondentOneAddress
                    #PostCode: respondentOneAddressPostCode
                    isAddressUnknown: respondentOneAddressDontKnow
                    landline: respondentOneHomePhoneNumber
                    phoneNumber: respondentOneMobilePhoneNumber
                    canYouProvidePhoneNumber: respondentOneMobilePhoneNumberDontKnow
                    email: respondentOneEmailAddress
                    canYouProvideEmailAddress: respondentOneEmailAddressDontKnow
                    #isAtAddressLessThan5Years: respondentOneLivedAtThisAddressForOverFiveYears
                    addressLivedLessThan5YearsDetails: respondentOneAllAddressesForLastFiveYears
                - value:
                    firstName: respondentTwoFirstName
                    lastName: respondentTwoLastName
                    previousName: respondentTwoPreviousNames
                    gender: respondentTwoGender
                    dateOfBirth: respondentTwoDateOfBirth
                    isDateOfBirthUnknown: respondentTwoDateOfBirthDontKnow
                    placeOfBirth: respondentTwoPlaceOfBirth
                    address:
                      AddressLine1: respondentTwoAddress
                    #PostCode: respondentTwoAddressPostCode
                    isAddressUnknown: respondentTwoAddressDontKnow
                    landline: respondentTwoHomePhoneNumber
                    phoneNumber: respondentTwoMobilePhoneNumber
                    canYouProvidePhoneNumber: respondentTwoMobilePhoneNumberDontKnow
                    email: respondentTwoEmailAddress
                    canYouProvideEmailAddress: respondentTwoEmailAddressDontKnow
                    #isAtAddressLessThan5Years: respondentTwoLivedAtThisAddressForOverFiveYears
                    addressLivedLessThan5YearsDetails: respondentTwoAllAddressesForLastFiveYears
              litigationCapacityFactors: factorAffectingLitigationCapacity
              litigationCapacityReferrals: assessmentByAdultLearningTeam
              litigationCapacityOtherFactors: factorsAffectingPersonInCourt
              caApplicant1ExternalFlags:
                groupId: caApplicant1
                visibility: External
              caApplicant1InternalFlags:
                groupId: caApplicant1
                visibility: Internal
              caApplicant2ExternalFlags:
                groupId: caApplicant2
                visibility: External
              caApplicant2InternalFlags:
                groupId: caApplicant2
                visibility: Internal
              caRespondent1ExternalFlags:
                groupId: caRespondent1
                visibility: External
              caRespondent1InternalFlags:
                groupId: caRespondent1
                visibility: Internal
              caRespondent2ExternalFlags:
                groupId: caRespondent2
                visibility: External
              caRespondent2InternalFlags:
                groupId: caRespondent2
                visibility: Internal

              #printFullName: printFullName
              #agreedBy: applicantSolicitorsFirmName
              #SignedDate: applicantAndApplicantsolicitorSignedDate
              #positionOrOfficeHeld: position_or_OfficeHeld
              #courtFeeConsent: courtFeeConsent
              #isInterpreterNeeded: applicantRequiresInterpreter
              #interpreterNeeds:
              #  - value:
              #      language: applicantRequiresInterpreter_otherParty_dialect
              #      otherAssistance: applicantRequiresInterpreter_otherParty_details
              #isIntermediaryNeeded: applicantRequiresInterpreter_intermediaryRequired
              #isSpecialArrangementsRequired: requiredSpecialAssistanceOrFacilities
              #reasonsForIntermediary: applicantRequiresInterpreter_intermediaryRequired_details
              #specialArrangementsRequired: requiredSpecialAssistanceOrFacilities_details
              #authorizedFamilyMediatorAddress: authorizedFamilyMediator_address
              #authorizedFamilyMediatorDate: authorizedFamilyMediator_date
