uk:
  gov:
    hmcts:
      form-validation:
        caseTypeofApplication:
          C100:
            mandatoryFields:
              - applicantOneFirstName
              - applicantOneLastName
              - applicant1_firstName
              - applicant1_lastName
              - respondentOneFirstName
              - respondentOneLastName
              - respondent1_firstName
              - respondent1_lastName
              - childArrangement_order
              - prohibitedSteps_order
              - specialIssue_order
              - natureofOrder
              - domesticAbuse
              - childAbduction
              - childAbuse
              - drugs_alcohol_substanceAbuse
              - otherSafety_or_welfareAbuse
              - askingPermissionForApplication
              - urgent_or_withoutHearing
              - previous_or_ongoingProceeding
              - isConsentOrder
              - international_or_factorsAffectingLitigation
              - welshRequired
              - child1_firstName
              - child1_lastName
              - child1_gender
              - child1_orderAppliedFor
              - child1_applicant1_relationship
              - child1_respondent1_relationship
              - child_living_with_Applicant
              - child_living_with_Respondent
              - child_living_with_others
              - ExistingCase_onEmergencyProtection_Care_or_supervisionOrder
              - section1RelatingToChildCompleted
              - section2Section3Section4RelatingToMediationCompleted
              - section5Section6RelatingToApplicationReasonCompleted
              - section7RelatingToOtherCourtFullyCompleted
              - section8Section9Section10FactorsAffectingProceedingsCompleted
              - section11RelatingToApplicantCompleted
              - sections12Section13Section14RelatingToRespondentAndOthersNoticeCompleted
              - section16RelatingToTruthStatementCompleted
              - applicantRequiresWelsh
              - applicantRequiresInterpreter
              - applicantRequiresInterpreter_intermediaryRequired
              - requiredSpecialAssistanceOrFacilities
              - applicantOneDateOfBirth
            optionalFields:
              - applicantOnePlaceOfBirth
              - applicant2_firstName
              - applicant2_lastName
              - respondent2_firstName
              - respondent2_lastName
              - child1_dateOfBirth
              - child2_firstName
              - child2_lastName
              - child2_dateOfBirth
              - child2_gender
              - child2_orderAppliedFor
              - child2_applicant1_relationship
              - child2_respondent1_relationship
              - child3_firstName
              - child3_lastName
              - child3_dateOfBirth
              - child3_gender
              - child3_orderAppliedFor
              - child3_applicant1_relationship
              - child3_respondent1_relationship
              - child4_firstName
              - child4_lastName
              - child4_dateOfBirth
              - child4_gender
              - child4_orderAppliedFor
              - child4_applicant1_relationship
              - child4_respondent1_relationship
              - childrenServicesAuthority
              - child1_localAuthority_or_socialWorker
              - child2_localAuthority_or_socialWorker
              - child3_localAuthority_or_socialWorker
              - child4_localAuthority_or_socialWorker
              - subject_to_childProtectionPlan
              - children_of_same_parent
              - children_parentsName
              - child_parentsName_collection
              - parentalResponsibilityDetails
              - child_living_with_others_details
              - fmcRegistrationNumber
              - familyMember_Intimation_on_No_MIAM
              - soleTraderName
              - authorizedFamilyMediator_address
              - authorizedFamilyMediator_date
              - permissionRequired
              - permissionRequiredReason
              - briefDetailsOnTheApplication
              - havePreviousParentingPlan
              - withoutNotice_frustrateTheOrder
              - withoutNotice_otherReasons_HearingDate_or_Year
              - withoutNotice_otherReasons_CAFCASS_Name_and_officeAddress
              - withoutNotice_emergency_Protection_Order
              - withoutNotice_supervisionOrder
              - withoutNotice_caseOrder
              - withoutNotice_childAbduction
              - withoutNotice_proceeding_for_NonMolestationOrder
              - withoutNotice_contact_or_residentOrder
              - withoutNotice_contact_or_residentOrder_withAdoptionOrder
              - withoutNotice_childMaintenanceOrder
              - withoutNotice_childArrangementOrder
              - internationalElement_Resident_of_another_state
              - internationalElement_Resident_of_another_state_details
              - internationalElement_jurisdictionIssue
              - withoutNotice_jurisdictionIssue_details
              - internationalElement_request_toCentral_or_Consular_authority
              - internationalElement_request_toCentral_or_Consular_authority_details
              - factorAffectingLitigationCapacity
              - applicantOnePreviousNames
              - applicantOneHomePhoneNumber
              - applicantOneMobilePhoneNumber
              - applicantOneEmailAddress
              - applicantOneAllAddressesForLastFiveYears
              - hasApplicantOneLivedAtThisAddressForOverFiveYears
              - hasApplicantTwoLivedAtThisAddressForOverFiveYears
              - applicantTwoFirstName
              - applicantTwoLastName
              - applicantTwoPreviousNames
              - applicantTwoGender
              - applicantTwoDateOfBirth
              - applicantTwoPlaceOfBirth
              - applicantTwoAddress
              - applicantTwoHomePhoneNumber
              - applicantTwoMobilePhoneNumber
              - applicantTwoEmailAddress
              - applicantTwoLivedAtThisAddressForOverFiveYears
              - applicantTwoAllAddressesForLastFiveYears
              - respondentOnePreviousNames
              - respondentOneDateOfBirth
              - respondentOneDateOfBirthDontKnow
              - respondentOnePlaceOfBirth
              - respondentOneAddress
              - respondentOneAddressDontKnow
              - respondentOneHomePhoneNumber
              - respondentOneMobilePhoneNumber
              - respondentOneMobilePhoneNumberDontKnow
              - respondentOneEmailAddress
              - respondentOneEmailAddressDontKnow
              - hasRespondentOneLivedAtThisAddressForOverFiveYears
              - respondentOneAllAddressesForLastFiveYears
              - respondentTwoPreviousNames
              - respondentTwoGender
              - respondentTwoDateOfBirth
              - respondentTwoDateOfBirthDontKnow
              - respondentTwoPlaceOfBirth
              - respondentTwoAddress
              - respondentTwoAddressDontKnow
              - respondentTwoHomePhoneNumber
              - respondentTwoMobilePhoneNumber
              - respondentTwoMobilePhoneNumberDontKnow
              - respondentTwoEmailAddress
              - respondentTwoEmailAddressDontKnow
              - respondentTwoAllAddressesForLastFiveYears
              - hasRespondentTwoLivedAtThisAddressForOverFiveYears
              - otherPeopleOneFirstName
              - otherPeopleOneLastName
              - otherPeopleOnePreviousName
              - otherPeopleOneGender
              - otherPeopleOneDateOfBirth
              - otherPeopleOneDateOfBirthDontKnow
              - otherPeopleOneAddress
              - otherPeopleOneAddressPostcode
              - otherPeopleOneAddressDontKnow
              - otherPeopleOneRelationshipWithChildren
              - otherPeopleTwoFirstName
              - otherPeopleTwoLastName
              - otherPeopleTwoPreviousName
              - otherPeopleTwoGender
              - otherPeopleTwoDateOfBirth
              - otherPeopleTwoDateOfBirthDontKnow
              - otherPeopleTwoAddress
              - otherPeopleTwoAddressPostcode
              - otherPeopleTwoAddressDontKnow
              - otherPeopleTwoRelationshipWithChildren
              - otherChildrenOneFullName
              - otherChildrenOneDateOfBirth
              - otherChildrenOneDateOfBirthDontKnow
              - otherChildrenOneGender
              - OtherChildrenOneRelationshipWithApplicant
              - OtherChildrenOneRelationshipWithRespondent
              - OtherChildrenTwoFullName
              - OtherChildrenTwoDateOfBirth
              - OtherChildrenTwoGender
              - OtherChildrenTwoDateOfBirthDontKnow
              - OtherChildrenTwoRelationshipWithApplicant
              - OtherChildrenTwoRelationshipWithRespondent
              - solicitorFirmName
              - solicitorTelephoneNumber
              - solicitorFaxNumber
              - printFullName
              - applicantSolicitorsFirmName
              - applicantAndApplicantSolicitorSigned
              - applicantAndApplicantsolicitorSignedDate
              - courtFee
              - isApplicantSolicitorPresent
              - attended_MIAM
              - exemption_to_attend_MIAM
              - noMIAM_domesticViolance
              - noMIAM_childProtectionConcerns
              - noMIAM_Urgency
              - noMIAM_PreviousAttendence
              - noMIAM_otherReasons
              - noMIAM_DVE_arrestedForSimilarOffence
              - noMIAM_DVE_relevantPoliceCaution
              - noMIAM_DVE_relevantCriminalProceeding
              - noMIAM_DVE_protectionNotice_DAbuseAct
              - noMIAM_DVE_protectiveInjunction
              - noMIAM_DVE_noCrossUndertakingGiven
              - noMIAM_DVE_copyOfFactFinding
              - noMIAM_DVE_expertEvidenceReport
              - noMIAM_DVE_healthProfessionalReport
              - noMIAM_DVE_healthProfessionalReport_2
              - noMIAM_DVE_ReferralHealthProfessionalReport
              - noMIAM_DVE_memberOf_MultiAgencyRiskAssessmentConferrance_letter
              - noMIAM_DVE_domesticViolenceAdvisor
              - noMIAM_DVE_independentSexualViolenceAdvisor_Letter
              - noMIAM_DVE_officerEmployed_localAuthority_letter
              - noMIAM_DVE_domesticViolenceSupportCharity_letter
              - noMIAM_DVE_domesticViolenceSupportCharity_refuge_letter
              - noMIAM_DVE_publicAuthority_confirmationLetter
              - noMIAM_DVE_secretaryOfState_letter
              - noMIAM_DVE_evidenceFinancialMatters
              - NoMIAM_subjectOfEnquiries_byLocalAuthority
              - NoMIAM_subjectOfCPP_byLocalAuthority
              - noMIAM_urgency_risk_to_life_liberty_or_safety
              - noMIAM_urgency_AnyDelayflag
              - noMIAM_urgency_riskOfHarm
              - noMIAM_urgency_removalFromUnitedKingdom
              - noMIAM_urgency_miscarriageOfJustice
              - noMIAM_urgency_financialHardship
              - noMIAM_urgency_irretrievableProblems
              - noMIAM_urgency_conflictWithOtherStateCourts
              - previousMIAM_nonCourtDisputeResolution_4month
              - previousMIAM_existingProceeding_exepmtMIAM
              - otherExemption_withoutNotice
              - otherExemption_byVirture_of_Rule12_3
              - otherExemption_mediator_notAvailableToConduct
              - otherExemption_disability_or_inabilityToAttend
              - otherExemption_NotSufficient_Respondent_ContactDetails
              - otherExemption_applicant_or_respondent_inPrison
              - otherExemption_additonalInformation
              - otherExemption_NoEvidence_reason
              - applicantOnlyAttended
              - attendedMIAMTogether
              - applicantAndRespondentParty_AttendedMIAMSeparately
              - respondentPartyArranged_ToAttendMIAMSeparately
              - mediationNotProceeding_applicantAttendedMIAMAlone
              - mediationNotProceeding_applicantsAndRespondentsAttendedMIAM
              - mediationNotProceeding_hasStartedButBrokenWithSomeIssue
              - order_direction_sought
              - urgency_reason
              - application_timetable
              - respondent_effort
              - reason_for_consideration
              - withoutNotice_abridged_or_informalNotice
              - withoutNotice_abridged_or_informalNotice_reasons
              - withoutNotice_frustrateTheOrder_reason
              - nameOfPartyWhoNeedsWelsh
              - applicantRequiresInterpreter_applicant
              - applicantRequiresInterpreter_respondent
              - applicantRequiresInterpreter_otherParty
              - applicantRequiresInterpreter_otherParty_details
              - applicantRequiresInterpreter_otherParty_dialect
              - applicantRequiresInterpreter_intermediaryRequired_details
              - requiredSpecialAssistanceOrFacilities_details
              - Attendence_separateWaitingRoom
              - Attendence_separateEntryAndExit
              - Attendence_privacyScreen
              - Attendence_joinHearingByVideo
              - solicitorFullName
              - solicitorAddress
              - solicitorDxNumber
              - solicitorPostcode
              - solicitorReference
              - solicitorFeeAccountNo
              - applicantSolicitorEmailAddress
              - Checklist_claimingMIAMExemption
              - noMIAM_DVE_relevantConviction
              - noMIAM_DVE_courtOrder
              - noMIAM_DVE_protectionNotice
              - assessmentByAdultLearningTeam
              - factorsAffectingPersonInCourt
              - familyMediationServiceName
              - applicantRequiresWelsh_1_Both
              - applicantRequiresWelsh_1_written
              - applicantRequiresWelsh_1_Spoken
              - nameOfPartyWhoNeedsWelsh_1






              - noMIAM_urgency_risk_to_unlawfulRemoval  # noMIAM_urgency_removalFromUnitedKingdom
              - noMIAM_urgency_risk_to_miscarriageOfJustice # noMIAM_urgency_miscarriageOfJustice
              - noMIAM_urgency_unreasonablehardship # noMIAM_urgency_financialHardship
              - NoMIAM_PreviousAttendenceReason # previousMIAM_nonCourtDisputeResolution_4month

              - respondentOneGender
              - respondentOneAddressPostCode
              - respondentOneLivedAtThisAddressForOverFiveYears
              - applicantOneGender
              - applicantOneAddress
              - applicantOneAddressPostCode
              - applicantOneLivedAtThisAddressForOverFiveYears
              - applicantTwoAddressPostCode
              - respondentTwoAddressPostCode
              - respondentTwoLivedAtThisAddressForOverFiveYears
              - solicitor_fee_account_No # solicitorFeeAccountNo
              - solicitor_email_address # applicantSolicitorEmailAddress
              - other_case_name_of_children
              - other_case_name_of_court
              - other_case_case_number
              - other_case_date_or_year
              - other_case_name_and_office
              - other_case_emergency_protection_order
              - other_case_supervision_order
              - other_case_care_order
              - other_case_childAbduction
              - other_case_proceeding_for_NonMolestatioNorder
              - other_case_proceeding_for_contact_or_resident_order
              - other_case_contact_or_residentOrder_withAdoptioNorder
              - other_case_childMaintenanceOrder
              - other_case_childArrangementOrder
              - requiredSpecialArrangementDetails # requiredSpecialAssistanceOrFacilities_details
              - otherPeopleOneRelationshipToChild #withChildren
              - otherPeopleTwoRelationshipToChild
              - otherChildrenOneRelationshipToApplicants
              - otherChildrenOneRelationshipToRespondents
              - OtherChildrenTwoRelationshipToApplicants
              - OtherChildrenTwoRelationshipToRespondents
              - position_or_OfficeHeld
              - courtFeeConsent
              - mediationNotSuitable_NoneOfTheRespondentsWillingToAttendMIAM
              - mediationNotSuitable_NoneOfTheRespondentsFailedToAttendMIAMWithoutGoodReason
              - mediationNotSuitable_forResolvingTheDispute
              - applicantOnly_AttendedMIAM
              - applicantOnly_AttendedMIAMTogether
              - family_Mediation_ServiceName #familyMediationServiceName
              - sole_TraderName #soleTraderName
            regexValidationFields:
              dateFields:
                fieldNames:
                  - child1_dateOfBirth
                  - child2_dateOfBirth
                  - child3_dateOfBirth
                  - child4_dateOfBirth
                  - respondentOneDateOfBirth
                  - respondentTwoDateOfBirth
                  - otherPeopleOneDateOfBirth
                  - otherPeopleTwoDateOfBirth
                  - otherChildrenOneDateOfBirth
                  - OtherChildrenTwoDateOfBirth
                regex: dd/MM/yyyy
              emailFields:
                fieldNames:
                  -
                regex: ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,6}$
              numericFields:
                fieldNames:
                  -
                regex: ^[0-9]*$
              postcodeFields:
                fieldNames:
                  -
                regex: ^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][ABD-HJLNP-UW-Z]{2}$
              phoneNumberFields:
                fieldNames:
                  - respondentOneHomePhoneNumber
                  - respondentOneMobilePhoneNumber
                  - respondentTwoHomePhoneNumber
                  - respondentTwoMobilePhoneNumber
                regex: ^(?:0|\+?44)(?:\d\s?){9,10}$
              faxNumberFields:
                fieldNames:
                  -
                regex:
              xorConditionalFields:
                fieldNames:
                  -
                regex:
