uk:
  gov:
    hmcts:
      transform:
        caseTypeofApplication:
          FL401:
            caseFields:
              CASE_TYPE_ID: PRLAPPS
              EVENT_ID: create-case-privatelaw-bs-fl401
            caseDataFields:
              typeOfApplicationOrders:
                orderType:
              orderWithoutGivingNoticeToRespondent:
                orderWithoutGivingNotice: orderWithout_GivingNotice
              reasonForOrderWithoutGivingNotice:
                reasonForOrderWithoutGivingNotice:
                futherDetails: orderWithoutGivingNotice_moreReason
              bailDetails:
                isRespondentAlreadyInBailCondition: respondentBailConditions
                bailConditionEndDate:
              anyOtherDtailsForWithoutNoticeOrder:
                otherDetails: situationCourtToKnow

              applicantsFL401:
                  firstName: applicantFirstName
                  lastName: applicantLastName
                  previousName: applicantPreviousNames
                  email: applicant_Email
                  phoneNumber: applicant_PhoneNumber
                  isAddressConfidential:
                  isPhoneNumberConfidential:
                  isEmailAddressConfidential:
                  applicantPreferredContact:
                  doTheyHaveLegalRepresentation: applicant_LegalRepresenationNeeded
                  solicitorTelephone: applicant_Solicitor_PhoneNumber
                  solicitorEmail: applicant_Solicitor_EmailAddress
                  solicitorReference: applicant_Solicitor_Reference
                  dxNumber: applicant_Solicitor_DXNumber
                  applicantContactInstructions: applicant_ContactInstructions
                  address:
                    AddressLine1: applicant_Address_BuildingAndStreet
                    AddressLine2: applicant_Address_SecondLine
                    PostTown: applicant_Address_TownOrCity
                    County: applicant_Address_County
                    PostCode: applicant_Address_Postcode
                  solicitorAddress:
                      AddressLine1: applicant_Solicitor_Address_BuildingAndStreet
                      AddressLine2: applicant_Solicitor_Address_SecondLine
                      PostTown: applicant_Solicitor_Address_TownOrCity
                      County: applicant_Solicitor_Address_County
                      PostCode: applicant_Solicitor_Address_Postcode

              respondentsFL401:
                firstName: respondentFirstName
                lastName: respondentLastName
                previousName: respondentPreviousNames
                email: respondent_Email
                phoneNumber: respondent_PhoneNumber
                address:
                  AddressLine1: respondent_Address_BuildingAndStreet
                  AddressLine2: respondent_Address_SecondLine
                  postTown: respondent_Address_TownOrCity
                  county: respondent_Address_County
                  postCode: respondent_Address_Postcode

              respondentRelationDateInfoObject:

              fl401StmtOfTruth:
                fullname: StatementOfTruth_FullName
                signature:
                nameOfFirm: StatementOfTruth_FirmName
                signOnBehalf: StatementOfTruth_PositionHeld

              applicationTypeDetails:
                typesOfApplication: orderApplyingFor_nonmolestation

              isInterpreterNeeded: InterpreterNeededAtCourt
              isDisabilityPresent: disabilitySupport_NeededAtCourt

              home:
                address:
                      AddressLine1: occupationOrderAddress_BuildingAndStreet
                      AddressLine2: occupationOrderAddress_SecondLine
                      PostTown: occupationOrderAddress_TownOrCity
                      PostCode: occupationOrderAddress_Postcode
                      County: occupationOrderAddress_County
                textAreaSomethingElse: occupationOrderAddress_CurrentOccupant_Others
                isPropertyAdapted: propertySpeciallyAdapted
                howIsThePropertyAdapted: propertySpeciallyAdapted_Details
                isThereMortgageOnProperty: MortgageOnProperty
                mortgages:
                      mortgageLenderName: MortgageLender_Name
                      address:
                            AddressLine1: MortgageLender_BuildingAndStreet
                            AddressLine2: MortgageLender_SecondLine
                            PostTown: MortgageLender_TownOrCity
                            County: MortgageLender_County
                            PostCode: MortgageLender_Postcode
                      mortgageNamedAfter:
                      textAreaSomethingElse: MortgageOnProperty_Person_Others
                      mortgageNumber: MortgageOnProperty_Number
                isPropertyRented: RentedProperty
                landlords:
                      textAreaSomethingElse: RentedProperty_Person_Others
                      landlordName: LandlordDetails_Name
                      address:
                            AddressLine1: LandlordDetails_BuildingAndStreet
                            AddressLine2: LandlordDetails_SecondLine
                            PostTown: LandlordDetails_TownOrCity
                            County: LandlordDetails_County
                            PostCode: LandlordDetails_Postcode
                doesApplicantHaveHomeRights: HomeRights
                furtherInformation: CourtToConsider
