uk:
  gov:
    hmcts:
      transform:
        caseTypeofApplication:
          A1:
            caseFields:
              CASE_TYPE_ID: PRLAPPS
              EVENT_ID: create-case-privatelaw-bs
            caseDataFields:
              applicant:
                - value:
                    applicantFullName: applicant_full_name #applicantFullName - not in use in prl-ccd-definition
                    applicantAddress: applicant_address #applicantAddress - not in use
                    addressPostCode: applicant_postcode #addressPostCode - not in use
                    applicantPhoneNumber: applicant_telephone_number #applicantPhoneNumber - not in use
                    applicantDateOfBirth: applicant_dateOfBirth #applicantDateOfBirth - not in use
                    reference: applicant_reference #reference - not in use
